### PR TITLE
New options for making particle lenses

### PR DESCRIPTION
**Pull request by rbmetcalf**
@gdespali @sampath215 @jwhsueh 

Hello all.  I have made a new way of creating LensHaloParticles from simulation data files.  

This is done through the `MakeParticleLenses` class.  Hopefully the doc explains it
[here](http://glenco.github.io/glamer/Doc/html/class_make_particle_lenses.html).

The calculation of the nearest neighbor smoothing distance should be much improved now.  I have been doing 100 million particles in less than an hour on 
my machine and just a few seconds for 100 thousand .  (Remember to set N_THREADS).

This branch will require a rebuild (cmake and make).

Please let me know at here if you have any trouble, think it could be better explained in the doc or have any idea for how it could be better implemented.

### CODE REVIEW

**Comment by rbmetcalf** [comment]
@jwhsueh I found something that might be causing your problem.  Try out the latest version and tell me if it goes away.

**Comment by rbmetcalf** [comment]
I made a mistake and was multiplying particle masses and positions by h instead of dividing.  This is corrected and should reduce the deflections, convergence, etc.  Sorry about that... It is corrected now.

I also corrected a glitch where the ordering of the points on the critical curves and caustic curves would not be correct in some cases.  This could have affected the reported area of the critical curve and caustics in some cases when the critical curve is complicated.

**Comment by jwhsueh** [comment]
Hi Ben,

I got the following error at compile after I pull the latest version:

concave_hull.h:367:43: error: return-statement with no value, in function returning ‘std::vector<T>’ [-fpermissive]
     if(init_points.size() == hull.size()) return;
                                           ^~~~~~
/data/users/hsueh/glamer/SLsimLib/include/concave_hull.h:381:27: error: return-statement with no value, in function returning ‘std::vector<T>’ [-fpermissive]
     if(edges.size() == 0) return;

**Comment by rbmetcalf** [comment]
Sorry about this everyone.  I found another bug.  
Because of my error in commenting my code previously, I was converting 
to physical particle position from comoving  one too many times.

I hope this doesn't cause you too much pain.  Thanks do to Massimo for noticing this.

**Comment by rbmetcalf** [comment]
I think this branch is working well.  I am merging it into the master now.

**Pull request merged**
