### PR TITLE
MOKAfits.cpp distance-redshift conversion

### PR DESCRIPTION
**Pull request by rbmetcalf**
Converted the inversion from comoving distance to redshift in MOKAfits.cpp to standard COMOLOGY method.

Requires updating CosmoLib.

@TiagoBsCastro 
@cgiocoli

### CODE REVIEW

**Comment by TiagoBsCastro** [comment]
Sorry guys, I thought it was a Glamer PR. But as I pointed out in the issue, the kernel of the problem is on line 228.

**Comment by rbmetcalf** [comment]
Has the problem been solved?

**Comment by TiagoBsCastro** [comment]
Sorry for my silence, Ben. I thought the issue was already closed... Mu mistake. Anyways, yes. The problem seems to be solved. Many thanks!

**Comment by rbmetcalf** [comment]
Excellent.  Thanks.

**Pull request merged**
